export enum Endpoints {
  AUTH = 'auth',
  CLIENT = 'client',
  USER = 'user',
  PRODUCT = 'product',
  INVOICE = 'invoice',
  ITEM_INVOICE = 'item_invoice',
  ITEM_BUDGET = 'item_budget',
  EMAIL = 'email',
  CONSTRUCTION = 'construction',
  EMPLOYEE = 'employee',
  DASHBOARD = 'dashboard',
  FILE = 'file',
  REQUEST_RETENTION = 'request_retention',
  BUDGET = 'budget',
  PARAMS_CONFIGURATION = 'params_configuration',
}

export enum OptionsEndPonits {
  LOGIN = 'login',
  PRINT_INVOICE_PDF = 'print_invoice_pdf',
  SEND_INVOICE_PDF = 'send_invoice_pdf',
  CREATE_EPI = 'print_epi_pdf',
  CREATE_MAQUINARIA = 'print_maquinaria_pdf',
  CREATE_AUTORIZACION = 'print_ficha_pdf',
  LOAD_PRODUCT = 'load_products',
  RECIEVETOTALRETENTION = 'receive_total_retention',
  RECIEVEHALFRETENTION = 'receive_half_retention',
  TOTALS = 'totals',
  TOTALS_MONTHS = 'totals_months',
  SUMMARY = 'summary',
  INVOICES = 'invoices',
  PERMIT_CHANGE_END_DATE = 'permit_change_end_date',
  PENDING = 'pending',
  SEND_REQUEST_RETENTION = 'send',
  PRINT_REQUEST_RETENTION = 'print_request_retention',
  UPDATE_RETENTIONS = 'update_retentions',
  PRINT_BUDGET_PDF = 'print_budget_pdf',
  SEND_BUDGET_PDF = 'send_budget_pdf',
  PRINT_SUMMARY_TRIMESTER_PDF = 'print_summary_trimester_pdf',
  SEND_SUMMARY_TRIMESTER_PDF = 'send_summary_trimester_pdf',
  DOWNLOAD_SUMMARY_TRIMESTER_PDF = 'download_summary_trimester_pdf',
}
